apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oficina-api
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: oficina.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oficina-api
                port:
                  number: 80
