apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oficina
resources:
  - namespace.yaml
  - postgres-pvc.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml

configMapGenerator:
  - name: oficina-api-config
    literals:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__Provider=Postgres
      - Database__UseMigrations=false
      - Jwt__Issuer=OficinaMvp
      - Jwt__Audience=OficinaMvpClients
      - Jwt__ExpirationMinutes=120
      - AdminCredentials__Username=admin
      - Notifications__Mode=Log
      - SeedDemoData=true

generatorOptions:
  disableNameSuffixHash: true
