apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oficina-postgres-data
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
